[package]
name = "zkmsg"
type = "contract"
authors = [""]
compiler_version = ">=0.26.0"

[dependencies]
# Framework import
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.32.0", directory="noir-projects/aztec-nr/aztec" }

# Utility dependencies
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.32.0", directory="noir-projects/aztec-nr/value-note"}